### ISSUE TITLE
ECS - Saving: Ensuring StarSystems are not serialized twice

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#92] opened 2015-10-11 23:17 UTC
At the moment it appears that it's saving multiple instances of earth colony when doing a default start.

**Comment by Rod-Serling** [comment] 2016-02-02 17:08
The problem is with the preservation of references for solar systems.
Save process currently simply serializes the Game class.

Problem occurs because when we save the global entity manager, we're saving faction info. Factions have references to StarSystems, JSON goes ahead and serializes the entire StarSystem inside the faction. That's what we need to prevent. We need to serialize only a reference to the StarSystem to be resolved later.

Later, when we go to save the StarSystems individually (From the Game class' reference), they're serialized again. We need to keep this serialization because this is where we serialize systems that have been generated but not discovered.

This should be accomplish-able with some tweaks to the JSON serializer, but it might get ugly due to some of the custom serialization/deserialization going on in the EntityManager.

**Comment by Rod-Serling** [comment] 2016-02-02 18:07
Fixed in commit 27da311

There's still an issue with FactionTechDB's not properly saving their dictionaries. Is there a reason we're not using JDictionaries there @se5a ?

**Comment by Rod-Serling** [comment] 2016-02-02 20:41
Savegames are now fully consistent (Save, loading from that save, and saving again produces the exact same output) with no issues with duplicate solar systems. I've pushed a test to help ensure this stays the same. I'm going to mark this as resolved and close it.

**Closed by Rod-Serling** 2016-02-02 20:41 UTC
Labels: bug, Developer Needed, High Priority
