### ISSUE TITLE
Game.GetSystems(authToken) can return duplicates. 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#168] opened 2016-07-09 20:51 UTC
Starting the game.
Chang the faction to SpaceMaster.
Attempt to open the SystemInfo tab.
will crash trying to add duplicate items to the dictionaryVM, _gameVM.Game.GetSystems(_gameVM.CurrentAuthToken); is returning a list with two Sol systems. (both have the same guid)

**Comment by DifferentLevelDan** [comment] 2017-04-30 06:47
Unable to reproduce on current builds. Seems to be resolved and this issue needs closing.

**Comment by se5a** [comment] 2017-05-01 11:16
It's defiantly still happening in the ECS-Crossplatform branch following the OP steps. 
line 56 of the systeminfoVM returns a list from Game.GetSystems()

https://github.com/Pulsar4xDevs/Pulsar4x/blob/ECS-CrossPlatform/Pulsar4X/ViewModelLib/ViewModels/SystemInfoVM.cs#L56

I traced the crash back that far but didn't trace it further.

**Closed as completed** 2017-05-03 17:56 UTC
